/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Panel.*;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * @author Julián <Julián at Google>
 */
public class Principal extends javax.swing.JFrame {

    AdministrarPersonas ap;
    VerPersonas vp;
    AdministrarRoles ar;
    AdministrarProgramas apr;
    AdministrarPeriodos ape;
    AdministrarDepartamentos ad;
    AdministrarCursos ac;
    AdministrarAsignaturas aa;
    AdministrarSalones as;
    AdministrarMatriculas am;
    VerHorario vh;
    public Principal() {
        initComponents();
        FlatMacDarkLaf.setup();
        ap=new AdministrarPersonas();
        vp=new VerPersonas();
        ar=new AdministrarRoles();
        apr=new AdministrarProgramas();
        ape=new AdministrarPeriodos();
        ad=new AdministrarDepartamentos();
        ac=new AdministrarCursos();
        aa=new AdministrarAsignaturas();
        as=new AdministrarSalones();
        am=new AdministrarMatriculas();
        vh=new VerHorario();
        
        add(ap);
        add(vp);
        add(ar);
        add(apr);
        add(ape);
        add(ad);
        add(ac);
        add(aa);
        add(as);
        add(am);
        add(vh);
        
        ap.setVisible(false);
        vp.setVisible(false);
        ar.setVisible(false);
        apr.setVisible(false);
        ape.setVisible(false);
        ad.setVisible(false);
        ac.setVisible(false);
        aa.setVisible(false);
        as.setVisible(false);
        am.setVisible(false);
        vh.setVisible(false);

        // Preguntar al usuario con un JOptionPane
        int opcion = JOptionPane.showOptionDialog(this, "¿Desea pantalla completa?", "Opciones", 
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, 
            new String[]{"Sí", "No"}, "No");

        // Establecer el tamaño del JFrame
        if (opcion == JOptionPane.YES_OPTION) {
            setExtendedState(JFrame.MAXIMIZED_BOTH); // Pantalla completa
        } else {
            setLocationRelativeTo(null); // Centrar en la pantalla
            setSize(1000, 600); // Tamaño mediano
        }

        ImageIcon imagenFondo = new ImageIcon("src\\main\\java\\img\\e1.jpg");
        // Crear el JLabel con la imagen de fondo
        JLabel labelFondo = new JLabel(imagenFondo);

        // Establecer el layout del contenido del JFrame como BorderLayout
        getContentPane().setLayout(new BorderLayout());

        // Agregar el JLabel al centro del JFrame
        getContentPane().add(labelFondo, BorderLayout.CENTER);

        // Ajustar la imagen después de que el JFrame se haya establecido en modo de pantalla completa
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Escalar la imagen para que se ajuste al tamaño del JLabel
                labelFondo.setIcon(new ImageIcon(imagenFondo.getImage().getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH)));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmiVentanaAdministrarPeriodos = new javax.swing.JMenuItem();
        jmiAdministrarDepartamentos = new javax.swing.JMenuItem();
        jmiAdministrarCursos = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jmiAdministrarAsignaturas = new javax.swing.JMenuItem();
        jmiMatriculas = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar3.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuBar3.setFocusCycleRoot(true);
        jMenuBar3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenu8.setText("Registros");
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem3.setText("Personas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuItem10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem10.setText("Programas");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jmiVentanaAdministrarPeriodos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiVentanaAdministrarPeriodos.setText("Periodos");
        jmiVentanaAdministrarPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVentanaAdministrarPeriodosActionPerformed(evt);
            }
        });
        jMenu8.add(jmiVentanaAdministrarPeriodos);

        jmiAdministrarDepartamentos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiAdministrarDepartamentos.setText("Departamentos");
        jmiAdministrarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdministrarDepartamentosActionPerformed(evt);
            }
        });
        jMenu8.add(jmiAdministrarDepartamentos);

        jmiAdministrarCursos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiAdministrarCursos.setText("Cursos");
        jmiAdministrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdministrarCursosActionPerformed(evt);
            }
        });
        jMenu8.add(jmiAdministrarCursos);

        jMenuItem13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem13.setText("Salones");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem13);

        jmiAdministrarAsignaturas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiAdministrarAsignaturas.setText("Asignaturas");
        jmiAdministrarAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdministrarAsignaturasActionPerformed(evt);
            }
        });
        jMenu8.add(jmiAdministrarAsignaturas);

        jmiMatriculas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmiMatriculas.setText("Matriculas");
        jmiMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMatriculasActionPerformed(evt);
            }
        });
        jMenu8.add(jmiMatriculas);

        jMenuBar3.add(jMenu8);

        jMenu9.setText("Asignaciones");
        jMenu9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem4.setText("Roles");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem4);

        jMenuItem12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem12.setText("Programas");
        jMenu9.add(jMenuItem12);

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem2.setText("Asignaturas");
        jMenu9.add(jMenuItem2);

        jMenuBar3.add(jMenu9);

        jMenu3.setText("Administraciónes");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem6.setText("Horarios");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem15.setText("Personas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuItem8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem8.setText("Profesores");
        jMenu3.add(jMenuItem8);

        jMenuItem7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem7.setText("Estudiantes");
        jMenu3.add(jMenuItem7);

        jMenuItem11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem11.setText("Programas");
        jMenu3.add(jMenuItem11);

        jMenuItem9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem9.setText("Asignaturas");
        jMenu3.add(jMenuItem9);

        jMenuItem14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem14.setText("Salones");
        jMenu3.add(jMenuItem14);

        jMenuBar3.add(jMenu3);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void colocarImagen(String imagen){
        // Eliminar el fondo actual si existe
        Component[] components = getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                getContentPane().remove(component);
                break; // Solo necesitamos eliminar un JLabel, ya que debería haber solo uno
            }
        }

        // Crear un nuevo fondo con la imagen deseada
        ImageIcon imagenFondo1 = new ImageIcon(imagen);
        JLabel labelFondo = new JLabel(imagenFondo1);

        // Ajustar el tamaño del fondo cuando se redimensiona el JFrame
        labelFondo.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                labelFondo.setIcon(new ImageIcon(imagenFondo1.getImage().getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH)));
            }
        });

        // Agregar el nuevo fondo al centro del JFrame
        getContentPane().add(labelFondo, BorderLayout.CENTER);

        // Repintar el JFrame para que los cambios sean visibles
        revalidate();
        repaint();
    }
    
    private void asignacionVentanas(Component ventana){
        ap.setVisible(false);
        vp.setVisible(false);
        ar.setVisible(false);
        apr.setVisible(false);
        ape.setVisible(false);
        ad.setVisible(false);
        ac.setVisible(false);
        aa.setVisible(false);
        as.setVisible(false);
        am.setVisible(false);
        vh.setVisible(false);
        ventana.setVisible(true);
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        asignacionVentanas(ap);
        
        colocarImagen("src\\main\\java\\img\\estudiantes3.jpg");
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmiAdministrarAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdministrarAsignaturasActionPerformed
        // TODO add your handling code here:
        asignacionVentanas(aa);
        colocarImagen("src\\main\\java\\img\\e26.jpg");
    }//GEN-LAST:event_jmiAdministrarAsignaturasActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        asignacionVentanas(as);
        colocarImagen("src\\main\\java\\img\\e22.jpg");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        asignacionVentanas(vp);
        
        colocarImagen("src\\main\\java\\img\\estudiantes3.jpg");
        
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        // Eliminar el fondo actual si existe
        asignacionVentanas(ar);
        
        colocarImagen("src\\main\\java\\img\\e14.jpg");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        asignacionVentanas(apr);
        
        colocarImagen("src\\main\\java\\img\\e6.jpg");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jmiVentanaAdministrarPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVentanaAdministrarPeriodosActionPerformed
        asignacionVentanas(ape);
        
        colocarImagen("src\\main\\java\\img\\e19.jpg");
    }//GEN-LAST:event_jmiVentanaAdministrarPeriodosActionPerformed

    private void jmiAdministrarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdministrarDepartamentosActionPerformed
        asignacionVentanas(ad);
        
        colocarImagen("src\\main\\java\\img\\e23.jpg");
    }//GEN-LAST:event_jmiAdministrarDepartamentosActionPerformed

    private void jmiAdministrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdministrarCursosActionPerformed
        // TODO add your handling code here:
        asignacionVentanas(ac);
        
        colocarImagen("src\\main\\java\\img\\e4.jpg");
    }//GEN-LAST:event_jmiAdministrarCursosActionPerformed

    private void jmiMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMatriculasActionPerformed
        // TODO add your handling code here:
        asignacionVentanas(am);
        
        colocarImagen("src\\main\\java\\img\\e28.jpg");
    }//GEN-LAST:event_jmiMatriculasActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        asignacionVentanas(vh);
        
        colocarImagen("src\\main\\java\\img\\e8.jpg");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new HiFiLookAndFeel());
        } catch (Exception e) {
        }
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jmiAdministrarAsignaturas;
    private javax.swing.JMenuItem jmiAdministrarCursos;
    private javax.swing.JMenuItem jmiAdministrarDepartamentos;
    private javax.swing.JMenuItem jmiMatriculas;
    private javax.swing.JMenuItem jmiVentanaAdministrarPeriodos;
    // End of variables declaration//GEN-END:variables
}
