package Panel;

import Model.Curso;
import Model.Departamento;
import Model.Periodo;
import Model.Pro_Per_Cur_Asig;
import Model.Programa;
import Repository.CursoImpl;
import Repository.DepartamentoImpl;
import Repository.PeriodoImpl;
import Repository.Pro_Per_Cur_AsigImpl;
import Repository.ProgramaImpl;
import Repository.Repository;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;

/**
 * @Julián
 */
public class AdministrarCursos extends javax.swing.JPanel {
    
    private static final Repository departamentoRepository= new DepartamentoImpl();
    private static final Repository programaRepository=new ProgramaImpl();
    private static final Repository cursoRepository=new CursoImpl();
    private static final Repository periodoRepository=new PeriodoImpl();
    private static final Repository multitablasRepository=new Pro_Per_Cur_AsigImpl();
    List<Departamento> listaDepartamentos=departamentoRepository.listar();
    List<Programa> listaProgramas=programaRepository.listar();
    List<Curso> listaCursos=cursoRepository.listar();
    List<Pro_Per_Cur_Asig> listaMultitablas=multitablasRepository.listar();
    List<Periodo> listaPeriodos=periodoRepository.listar();
    
    public AdministrarCursos() {
        initComponents();
        
        setSize(1000, 600); // Tamaño mediano
        jtfCodigoDepartamento.setVisible(false);
        jbActualizar.setVisible(false);
        jbRegistrar.setVisible(true);
        
        jifDatosDepartamento.setVisible(false);
        jcbSemestre.setVisible(true);
//        rellenarSemestres();
        
        for (Programa programa : listaProgramas) {
            jcbProgramas.addItem(programa.getNombre());
        }
        
        for (Departamento departamento : listaDepartamentos) {
            jcbDepartamentos.addItem(departamento.getDepartamento_nombre());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbSeleccion = new javax.swing.JComboBox<>();
        jbRegistrar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jtfCodigoDepartamento = new javax.swing.JTextField();
        jifDatosDepartamento = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNombreCurso = new javax.swing.JTextField();
        jcbSemestre = new javax.swing.JComboBox<>();
        jcbDepartamentos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaGuiaCatedra = new javax.swing.JTextArea();
        jcbProgramas = new javax.swing.JComboBox<>();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbSeleccion.setBackground(new java.awt.Color(178, 144, 73));
        jcbSeleccion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbSeleccion.setForeground(new java.awt.Color(0, 0, 1));
        jcbSeleccion.setMaximumRowCount(5);
        jcbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar", "Modificar" }));
        jcbSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Que desea hacer?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(0, 0, 1))); // NOI18N
        jcbSeleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionActionPerformed(evt);
            }
        });
        add(jcbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 169, 40));

        jbRegistrar.setBackground(new java.awt.Color(0, 0, 1));
        jbRegistrar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbRegistrar.setForeground(new java.awt.Color(178, 144, 73));
        jbRegistrar.setText("Registrar");
        jbRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });
        add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 100, 30));

        jbActualizar.setBackground(new java.awt.Color(0, 0, 1));
        jbActualizar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(178, 144, 73));
        jbActualizar.setText("Actualizar");
        jbActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 100, 30));

        jtfCodigoDepartamento.setBackground(new java.awt.Color(178, 144, 73));
        jtfCodigoDepartamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfCodigoDepartamento.setForeground(new java.awt.Color(0, 0, 1));
        jtfCodigoDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Codigo del Curso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfCodigoDepartamento.setOpaque(true);
        jtfCodigoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoDepartamentoActionPerformed(evt);
            }
        });
        jtfCodigoDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoDepartamentoKeyReleased(evt);
            }
        });
        add(jtfCodigoDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 169, -1));

        jifDatosDepartamento.setTitle("Datos del departamento");
        jifDatosDepartamento.setVisible(true);
        jifDatosDepartamento.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        jifDatosDepartamento.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 24));

        jlNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNombre.setText("no tiene nombre");
        jlNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jifDatosDepartamento.getContentPane().add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 303, 24));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Codigo:");
        jifDatosDepartamento.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 83, 24));

        jlCodigo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlCodigo.setText("No tiene codigo");
        jifDatosDepartamento.getContentPane().add(jlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 100, 24));

        add(jifDatosDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 310, 240));

        jLabel3.setBackground(new java.awt.Color(242, 242, 150));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Aquí podrá registrar y actualizar Cursos");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 380, 40));

        jLabel4.setBackground(new java.awt.Color(242, 242, 150));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("digite numero de Cursos para ver si existe");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 400, 40));

        jtfNombreCurso.setBackground(new java.awt.Color(178, 144, 73));
        jtfNombreCurso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfNombreCurso.setForeground(new java.awt.Color(0, 0, 1));
        jtfNombreCurso.setToolTipText("");
        jtfNombreCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Nombre del Curso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfNombreCurso.setOpaque(true);
        add(jtfNombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, -1));

        jcbSemestre.setBackground(new java.awt.Color(166, 181, 167));
        jcbSemestre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbSemestre.setForeground(new java.awt.Color(0, 0, 1));
        jcbSemestre.setMaximumRowCount(5);
        jcbSemestre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Semestre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(0, 0, 1))); // NOI18N
        jcbSemestre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSemestreActionPerformed(evt);
            }
        });
        add(jcbSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 80, 40));

        jcbDepartamentos.setBackground(new java.awt.Color(166, 181, 167));
        jcbDepartamentos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbDepartamentos.setForeground(new java.awt.Color(0, 0, 1));
        jcbDepartamentos.setMaximumRowCount(5);
        jcbDepartamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Departamentos Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(0, 0, 1))); // NOI18N
        jcbDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDepartamentosActionPerformed(evt);
            }
        });
        add(jcbDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 220, 40));

        jtaGuiaCatedra.setBackground(new java.awt.Color(166, 181, 167));
        jtaGuiaCatedra.setColumns(20);
        jtaGuiaCatedra.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtaGuiaCatedra.setForeground(new java.awt.Color(0, 0, 1));
        jtaGuiaCatedra.setLineWrap(true);
        jtaGuiaCatedra.setRows(5);
        jtaGuiaCatedra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 254)), "Guía Catedra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 254))); // NOI18N
        jScrollPane1.setViewportView(jtaGuiaCatedra);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 300, 210));

        jcbProgramas.setBackground(new java.awt.Color(166, 181, 167));
        jcbProgramas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbProgramas.setForeground(new java.awt.Color(0, 0, 1));
        jcbProgramas.setMaximumRowCount(5);
        jcbProgramas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Programas Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(0, 0, 1))); // NOI18N
        jcbProgramas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbProgramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProgramasActionPerformed(evt);
            }
        });
        add(jcbProgramas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarListas(){
        listaProgramas=programaRepository.listar();
        listaMultitablas=multitablasRepository.listar();
        listaPeriodos=periodoRepository.listar();
        listaCursos=cursoRepository.listar();
    }
    
    private Curso datosCurso(){
        Curso c=new Curso();
        String nombre=jtfNombreCurso.getText();
        String guiaCatedra=jtaGuiaCatedra.getText();
        String nombreDepartamento=(String) jcbDepartamentos.getSelectedItem();
        int codigoDepartamento=0;
         for (Departamento departamento : listaDepartamentos) {
             if(nombreDepartamento.equals(departamento.getDepartamento_nombre())){
                 codigoDepartamento=departamento.getDepartamento_id();
                 break;
             }
        }
         c.setCurso_nombre(nombre);
         c.setDepartamento_id(codigoDepartamento);
         c.setGuia_catedra(guiaCatedra);
        return c;
    }
    
    private Pro_Per_Cur_Asig datosMultitabla(){
        Pro_Per_Cur_Asig m=new Pro_Per_Cur_Asig();
        actualizarListas();
        ArrayList<Integer> listaIdPeriodos = new ArrayList<>();
        String programa_seleccionado=(String) jcbProgramas.getSelectedItem();
        String semestreSeleccionadoStr = (String) jcbSemestre.getSelectedItem();
        int semestreSeleccionadoInt = Integer.parseInt(semestreSeleccionadoStr);
        byte semestreSeleccionado = (byte) semestreSeleccionadoInt;

        int codigoPrograma=0,codigoCurso=0,codigoPeriodo=0;
        
        for (Programa programa : listaProgramas) {
            if(programa_seleccionado.equals(programa.getNombre())){
                codigoPrograma=programa.getPrograma_id();
            }
        }
        for (Pro_Per_Cur_Asig multi : listaMultitablas) {
            if(codigoPrograma==multi.getPrograma_id()){
                listaIdPeriodos.add(multi.getPeriodo_id());
            }
        }
        for (Periodo periodo : listaPeriodos) {
            for (Integer IdPeriodo : listaIdPeriodos) {
                if (IdPeriodo==periodo.getPeriodo_id()) {
                    if(semestreSeleccionado==periodo.getPeriodo_numero_semestre()){
                        codigoPeriodo=periodo.getPeriodo_id();
                    }
                }
            }
        }
        
        for (int i = listaCursos.size()-1; i >= 0; i--) {
            Curso curso = listaCursos.get(i);
            codigoCurso=curso.getCurso_id();
            break;
        }
        m.setCurso_id(codigoCurso);
        m.setPeriodo_id(codigoPeriodo);
        m.setPrograma_id(codigoPrograma);
        return m;
    }
    
    private void lecturaModalCurso(){
        jifDatosDepartamento.setVisible(true);
        Departamento d=(Departamento) departamentoRepository.porCodigo(Integer.parseInt(jtfCodigoDepartamento.getText()));
        jlNombre.setText(d.getDepartamento_nombre());
        jlCodigo.setText(String.valueOf(d.getDepartamento_id()));
    }
    
    private void rellenarSemestres(){
        actualizarListas();
        String programa_seleccionado=(String) jcbProgramas.getSelectedItem();
        int codigo_programa=0;
        jcbSemestre.removeAllItems();
        TreeSet<Integer> listaIdPeriodos = new TreeSet<>();
        if(programa_seleccionado!=null){
            for (Programa programa : listaProgramas) {
                if(programa_seleccionado.equals(programa.getNombre())){
                    codigo_programa=programa.getPrograma_id();
                }
            }
            for (Pro_Per_Cur_Asig multi : listaMultitablas) {
                if(codigo_programa==multi.getPrograma_id()){
                    listaIdPeriodos.add(multi.getPeriodo_id());
                }
            }
            
            for (Periodo periodo : listaPeriodos) {
                for (Integer IdPeriodo : listaIdPeriodos) {
                    if (IdPeriodo.equals(periodo.getPeriodo_id())) {
                        jcbSemestre.addItem(String.valueOf(periodo.getPeriodo_numero_semestre()));
                    }
                }
            }
        }else if(programa_seleccionado==null){
            jcbSemestre.setVisible(false);
        }
    }
    
    private void jcbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionActionPerformed
        // TODO add your handling code here:
        String seleccion=(String)jcbSeleccion.getSelectedItem();
        if(seleccion.equals("Registrar")){
            jtfCodigoDepartamento.setVisible(false);
            jbActualizar.setVisible(false);
            jbRegistrar.setVisible(true);
        }else if(seleccion.equals("Modificar")){
            jtfCodigoDepartamento.setVisible(true);
            jbActualizar.setVisible(true);
            jbRegistrar.setVisible(false);
        }
    }//GEN-LAST:event_jcbSeleccionActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        
        cursoRepository.guardar(datosCurso());
        multitablasRepository.guardar(datosMultitabla());
        JOptionPane.showMessageDialog(null, "Datos guardados");
        
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        cursoRepository.modificar(datosCurso());
        lecturaModalCurso();
        JOptionPane.showMessageDialog(null, "Datos modificados");

    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtfCodigoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoDepartamentoActionPerformed

    private void jtfCodigoDepartamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoDepartamentoKeyReleased
        // TODO add your handling code here:
        
        if(jtfCodigoDepartamento.getText().equals("")){
            jifDatosDepartamento.setVisible(false);
        }else{
            lecturaModalCurso();
        }
        
        
    }//GEN-LAST:event_jtfCodigoDepartamentoKeyReleased

    private void jcbDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDepartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDepartamentosActionPerformed

    private void jcbSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSemestreActionPerformed
        // TODO add your handling code here:
        String seleccion=(String)jcbSeleccion.getSelectedItem();
        if(seleccion.equals("Asignar")){
            jbActualizar.setVisible(false);
            jbRegistrar.setVisible(true);
        }else if(seleccion.equals("Eliminar")){
            jbActualizar.setVisible(true);
            jbRegistrar.setVisible(false);
        }
    }//GEN-LAST:event_jcbSemestreActionPerformed

    private void jcbProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProgramasActionPerformed
        // TODO add your handling code here:
        rellenarSemestres();
    }//GEN-LAST:event_jcbProgramasActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox<String> jcbDepartamentos;
    private javax.swing.JComboBox<String> jcbProgramas;
    private javax.swing.JComboBox<String> jcbSeleccion;
    private javax.swing.JComboBox<String> jcbSemestre;
    private javax.swing.JInternalFrame jifDatosDepartamento;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextArea jtaGuiaCatedra;
    private javax.swing.JTextField jtfCodigoDepartamento;
    private javax.swing.JTextField jtfNombreCurso;
    // End of variables declaration//GEN-END:variables
}
