package Panel;

import Model.Departamento;
import Model.Periodo;
import Model.Programa;
import Repository.DepartamentoImpl;
import Repository.Repository;
import javax.swing.JOptionPane;

/**
 * @Julián
 */
public class AdministrarDepartamentos extends javax.swing.JPanel {
    
    private static final Repository departamentoRepository= new DepartamentoImpl();
    
    public AdministrarDepartamentos() {
        initComponents();
        
        setSize(1000, 600); // Tamaño mediano
        jtfCodigoDepartamento.setVisible(false);
        jbActualizar.setVisible(false);
        jbRegistrar.setVisible(true);
        
        jifDatosDepartamento.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbSeleccion = new javax.swing.JComboBox<>();
        jbRegistrar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jtfCodigoDepartamento = new javax.swing.JTextField();
        jifDatosDepartamento = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNombreDepartamento = new javax.swing.JTextField();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbSeleccion.setBackground(new java.awt.Color(178, 144, 73));
        jcbSeleccion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbSeleccion.setForeground(new java.awt.Color(0, 0, 1));
        jcbSeleccion.setMaximumRowCount(5);
        jcbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar", "Modificar" }));
        jcbSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Que desea hacer?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(0, 0, 1))); // NOI18N
        jcbSeleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionActionPerformed(evt);
            }
        });
        add(jcbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 169, 40));

        jbRegistrar.setBackground(new java.awt.Color(0, 0, 1));
        jbRegistrar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbRegistrar.setForeground(new java.awt.Color(178, 144, 73));
        jbRegistrar.setText("Registrar");
        jbRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });
        add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 100, 30));

        jbActualizar.setBackground(new java.awt.Color(0, 0, 1));
        jbActualizar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(178, 144, 73));
        jbActualizar.setText("Actualizar");
        jbActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 100, 30));

        jtfCodigoDepartamento.setBackground(new java.awt.Color(178, 144, 73));
        jtfCodigoDepartamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfCodigoDepartamento.setForeground(new java.awt.Color(0, 0, 1));
        jtfCodigoDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Codigo del Departamento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfCodigoDepartamento.setOpaque(true);
        jtfCodigoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoDepartamentoActionPerformed(evt);
            }
        });
        jtfCodigoDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoDepartamentoKeyReleased(evt);
            }
        });
        add(jtfCodigoDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 169, -1));

        jifDatosDepartamento.setTitle("Datos del departamento");
        jifDatosDepartamento.setVisible(true);
        jifDatosDepartamento.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        jifDatosDepartamento.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 24));

        jlNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNombre.setText("no tiene nombre");
        jlNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jifDatosDepartamento.getContentPane().add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 303, 24));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Codigo:");
        jifDatosDepartamento.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 83, 24));

        jlCodigo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlCodigo.setText("No tiene codigo");
        jifDatosDepartamento.getContentPane().add(jlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 100, 24));

        add(jifDatosDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 390, 170));

        jLabel3.setBackground(new java.awt.Color(242, 242, 150));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Aquí podrá registrar y actualizar Departamentos");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 380, 40));

        jLabel4.setBackground(new java.awt.Color(242, 242, 150));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("digite numero de Departamento para ver si existe");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 400, 40));

        jtfNombreDepartamento.setBackground(new java.awt.Color(178, 144, 73));
        jtfNombreDepartamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfNombreDepartamento.setForeground(new java.awt.Color(0, 0, 1));
        jtfNombreDepartamento.setToolTipText("");
        jtfNombreDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Nombre del departamento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfNombreDepartamento.setOpaque(true);
        add(jtfNombreDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 440, -1));
    }// </editor-fold>//GEN-END:initComponents

    private Departamento datosDepartamento(){
        Departamento d=new Departamento();
        String nombre=jtfNombreDepartamento.getText();
        
        if(jtfCodigoDepartamento.getText().equals("")){
            System.out.println("guardando datos...");
        }else{
            int codigo=Integer.parseInt(jtfCodigoDepartamento.getText());
            d.setDepartamento_id(codigo);
        }
        d.setDepartamento_nombre(nombre);
        return d;
    }
    
    private void lecturaModalDepartamento(){
        jifDatosDepartamento.setVisible(true);
        Departamento d=(Departamento) departamentoRepository.porCodigo(Integer.parseInt(jtfCodigoDepartamento.getText()));
        jlNombre.setText(d.getDepartamento_nombre());
        jlCodigo.setText(String.valueOf(d.getDepartamento_id()));
    }
    
    private void jcbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionActionPerformed
        // TODO add your handling code here:
        String seleccion=(String)jcbSeleccion.getSelectedItem();
        if(seleccion.equals("Registrar")){
            jtfCodigoDepartamento.setVisible(false);
            jbActualizar.setVisible(false);
            jbRegistrar.setVisible(true);
        }else if(seleccion.equals("Modificar")){
            jtfCodigoDepartamento.setVisible(true);
            jbActualizar.setVisible(true);
            jbRegistrar.setVisible(false);
        }
    }//GEN-LAST:event_jcbSeleccionActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        
        departamentoRepository.guardar(datosDepartamento());
//        lecturaModal();
        JOptionPane.showMessageDialog(null, "Datos guardados");
        
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        departamentoRepository.modificar(datosDepartamento());
        lecturaModalDepartamento();
        JOptionPane.showMessageDialog(null, "Datos modificados");

    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtfCodigoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoDepartamentoActionPerformed

    private void jtfCodigoDepartamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoDepartamentoKeyReleased
        // TODO add your handling code here:
        
        if(jtfCodigoDepartamento.getText().equals("")){
            jifDatosDepartamento.setVisible(false);
        }else{
            lecturaModalDepartamento();
        }
        
        
    }//GEN-LAST:event_jtfCodigoDepartamentoKeyReleased

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox<String> jcbSeleccion;
    private javax.swing.JInternalFrame jifDatosDepartamento;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextField jtfCodigoDepartamento;
    private javax.swing.JTextField jtfNombreDepartamento;
    // End of variables declaration//GEN-END:variables
}
