package Panel;

import Model.Ciudad;
import Model.Curso;
import Model.Direccion;
import Model.Periodo;
import Model.Persona;
import Model.Pro_Per_Cur_Asig;
import Model.Programa;
import Repository.CiudadImpl;
import Repository.DireccionImpl;
import Repository.PeriodoImpl;
import Repository.PersonaImpl;
import Repository.Pro_Per_Cur_AsigImpl;
import Repository.ProgramaImpl;
import Repository.Repository;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @Julián
 */
public class AdministrarPeriodos extends javax.swing.JPanel {
    
    private static Repository programaRepository= new ProgramaImpl();
    private static Repository periodoRepository= new PeriodoImpl();
    private static final Repository multitablasRepository=new Pro_Per_Cur_AsigImpl();
    List<Programa> listaProgramas=programaRepository.listar();
    
    
    public AdministrarPeriodos() {
        initComponents();
        
        setSize(1000, 600); // Tamaño mediano
        jtfCodigo.setVisible(false);
        jbActualizar.setVisible(false);
        jbRegistrar.setVisible(true);
        
        jifDatosPrograma.setVisible(false);
        jifDatosPeriodo.setVisible(false);
        
        for (Programa programa : listaProgramas) {
            jcbProgramas.addItem(programa.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbSeleccion = new javax.swing.JComboBox<>();
        jbRegistrar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JTextField();
        jcbNumeroDelSemestre = new javax.swing.JComboBox<>();
        jifDatosPrograma = new javax.swing.JInternalFrame();
        jifDatosPeriodo = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlsemestre = new javax.swing.JLabel();
        jlCodigoPeriodo = new javax.swing.JLabel();
        jlCodigoDinamico = new javax.swing.JLabel();
        jlAño = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlNivel = new javax.swing.JLabel();
        jlNumeroSemestre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfAnioPeriodo = new javax.swing.JTextField();
        jcbProgramas = new javax.swing.JComboBox<>();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbSeleccion.setBackground(new java.awt.Color(178, 144, 73));
        jcbSeleccion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbSeleccion.setForeground(new java.awt.Color(0, 0, 1));
        jcbSeleccion.setMaximumRowCount(5);
        jcbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar", "Modificar" }));
        jcbSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Que desea hacer?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(0, 0, 1))); // NOI18N
        jcbSeleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionActionPerformed(evt);
            }
        });
        add(jcbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 169, 40));

        jbRegistrar.setBackground(new java.awt.Color(0, 0, 1));
        jbRegistrar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbRegistrar.setForeground(new java.awt.Color(178, 144, 73));
        jbRegistrar.setText("Registrar");
        jbRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });
        add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 100, 30));

        jbActualizar.setBackground(new java.awt.Color(0, 0, 1));
        jbActualizar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(178, 144, 73));
        jbActualizar.setText("Actualizar");
        jbActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 100, 30));

        jtfCodigo.setBackground(new java.awt.Color(178, 144, 73));
        jtfCodigo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfCodigo.setForeground(new java.awt.Color(0, 0, 1));
        jtfCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Codigo del Periodo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfCodigo.setOpaque(true);
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyReleased(evt);
            }
        });
        add(jtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 169, -1));

        jcbNumeroDelSemestre.setBackground(new java.awt.Color(166, 181, 167));
        jcbNumeroDelSemestre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbNumeroDelSemestre.setForeground(new java.awt.Color(0, 0, 1));
        jcbNumeroDelSemestre.setMaximumRowCount(5);
        jcbNumeroDelSemestre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Semestre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jcbNumeroDelSemestre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jcbNumeroDelSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 80, 40));

        jifDatosPrograma.setTitle("Datos de la Carrera");
        jifDatosPrograma.setVisible(true);
        jifDatosPrograma.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jifDatosPeriodo.setTitle("Datos Periodo");
        jifDatosPeriodo.setVisible(true);
        jifDatosPeriodo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Numero del Semestre:");
        jifDatosPeriodo.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 140, 24));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setText("Codigo:");
        jifDatosPeriodo.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 83, 24));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setText("Codigo Dinamico:");
        jifDatosPeriodo.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 24));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setText("Año:");
        jifDatosPeriodo.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 24));

        jlsemestre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlsemestre.setText("No tiene semestre");
        jifDatosPeriodo.getContentPane().add(jlsemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 152, 24));

        jlCodigoPeriodo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlCodigoPeriodo.setText("No tiene codigo");
        jifDatosPeriodo.getContentPane().add(jlCodigoPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 152, 24));

        jlCodigoDinamico.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlCodigoDinamico.setText("No tiene codigo");
        jifDatosPeriodo.getContentPane().add(jlCodigoDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 152, 24));

        jlAño.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlAño.setText("No tiene año");
        jifDatosPeriodo.getContentPane().add(jlAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 152, 24));

        jifDatosPrograma.getContentPane().add(jifDatosPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 380, 240));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        jifDatosPrograma.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 24));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Nivel:");
        jifDatosPrograma.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 109, 83, 24));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setText("Numeros semestres:");
        jifDatosPrograma.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 139, 127, 24));

        jlNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNombre.setText("no tiene nombre");
        jlNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jifDatosPrograma.getContentPane().add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 303, 24));

        jlNivel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNivel.setText("No tiene nivel");
        jifDatosPrograma.getContentPane().add(jlNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 109, 149, 24));

        jlNumeroSemestre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNumeroSemestre.setText("No tiene semestres");
        jifDatosPrograma.getContentPane().add(jlNumeroSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 139, -1, 24));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Codigo:");
        jifDatosPrograma.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 77, 83, 24));

        jlCodigo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlCodigo.setText("No tiene codigo");
        jifDatosPrograma.getContentPane().add(jlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 77, 152, 24));

        add(jifDatosPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 390, 240));

        jLabel3.setBackground(new java.awt.Color(242, 242, 150));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Aquí podrá registrar y actualizar periodos");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 330, 40));

        jLabel4.setBackground(new java.awt.Color(242, 242, 150));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("digite numero de periodo para ver si existe");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 340, 40));

        jtfAnioPeriodo.setBackground(new java.awt.Color(166, 181, 167));
        jtfAnioPeriodo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfAnioPeriodo.setForeground(new java.awt.Color(0, 0, 1));
        jtfAnioPeriodo.setToolTipText("");
        jtfAnioPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Año del periodo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfAnioPeriodo.setOpaque(true);
        add(jtfAnioPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, -1));

        jcbProgramas.setBackground(new java.awt.Color(166, 181, 167));
        jcbProgramas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbProgramas.setForeground(new java.awt.Color(0, 0, 1));
        jcbProgramas.setMaximumRowCount(5);
        jcbProgramas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Programas Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(0, 0, 1))); // NOI18N
        jcbProgramas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbProgramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProgramasActionPerformed(evt);
            }
        });
        add(jcbProgramas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private Periodo datosPeriodo(){
        Periodo p=new Periodo();
//        int codigoCarrera=Integer.parseInt(jtfCodigoCarrera.getText());
        short anio=Short.parseShort(jtfAnioPeriodo.getText());
        byte numeroSemestre=Byte.parseByte((String) jcbNumeroDelSemestre.getSelectedItem());
        if(jcbSeleccion.getSelectedItem().equals("Modificar")){
            int codigo=Integer.parseInt(jtfCodigo.getText());
            p.setPeriodo_id(codigo);
        }
        String codigoDinamico="P"+anio+"-"+numeroSemestre;
//        p.setPrograma_id(codigoCarrera);
        p.setPeriodo_codigo(codigoDinamico);
        p.setPeriodo_anio(anio);
        p.setPeriodo_numero_semestre(numeroSemestre);
        return p;
    }
    
    private Programa datosPrograma(){
        Programa p=new Programa();
        if(jcbSeleccion.getSelectedItem().equals("Modificar")){
            int codigo=Integer.parseInt(jtfCodigo.getText());
            p.setPrograma_id(codigo);
        }
        String nombre_programa=(String) jcbProgramas.getSelectedItem();
        byte cantidad_semestres=0;
        for (Programa programa : listaProgramas) {
            if(nombre_programa.equals(programa.getNombre())){
                cantidad_semestres=(byte) programa.getCantidad_semestres();
                break;
            }
        }
//        String nombre_programa=jtfNombrePrograma.getText();
        String nivel_programa=(String) jcbNumeroDelSemestre.getSelectedItem();
        p.setCantidad_semestres(cantidad_semestres);
        p.setNivel(nivel_programa);
//        p.setNombre(nombre_programa);
        return p;
    }
    
    private Pro_Per_Cur_Asig datosMultitabla(){
        List<Periodo> listaPeriodos=periodoRepository.listar();
        Pro_Per_Cur_Asig m=new Pro_Per_Cur_Asig();
        int codigoPrograma=0,codigo_periodo=0;
        String nombrePrograma=(String) jcbProgramas.getSelectedItem();
        for (Programa programa : listaProgramas) {
            if(nombrePrograma.equals(programa.getNombre())){
                codigoPrograma=programa.getPrograma_id();
                break;
            }
        }
        for (int i = listaPeriodos.size()-2; i >= 0; i--) {
            Periodo periodo = listaPeriodos.get(i);
            codigo_periodo=periodo.getPeriodo_id()+1;
            break;
        }
        System.out.println(codigo_periodo);
        m.setPrograma_id(codigoPrograma);
        m.setPeriodo_id(codigo_periodo);
        return m;
    }
    
    private void lecturaModal(){
        jifDatosPrograma.setVisible(true);
        jifDatosPeriodo.setVisible(false);
        jcbNumeroDelSemestre.removeAllItems();
        jifDatosPrograma.setTitle("Datos del programa");
        List<Programa> listaProgramas=programaRepository.listar();
        String nombre_programa=(String) jcbProgramas.getSelectedItem();
        for (Programa p : listaProgramas) {
            if(nombre_programa.equals(p.getNombre())){
                for (byte i = 1; i <= p.getCantidad_semestres(); i++) {
                    jcbNumeroDelSemestre.addItem(String.valueOf(i));
                }
                jlCodigo.setText(String.valueOf(p.getPrograma_id()));
                jlNivel.setText(p.getNivel());
                jlNombre.setText(p.getNombre());
                jlNumeroSemestre.setText(String.valueOf(p.getCantidad_semestres()));
                break;
            }
        }
    }
    
    private void lecturaModalPeriodo(){
        jifDatosPeriodo.setVisible(true);
        jifDatosPrograma.setVisible(true);
        int idPrograma=0,idPeriodo=Integer.parseInt(jtfCodigo.getText());
        Periodo pe=(Periodo) periodoRepository.porCodigo(idPeriodo);
        Programa pr=(Programa) programaRepository.porCodigo(pe.getPrograma_id());
        jifDatosPrograma.setTitle(pr.getNombre());
        jlCodigoDinamico.setText(pe.getPeriodo_codigo());
        jlCodigoPeriodo.setText(String.valueOf(pe.getPeriodo_id()));
        jlsemestre.setText(String.valueOf(pe.getPeriodo_numero_semestre()));
        jlAño.setText(String.valueOf(pe.getPeriodo_anio()));
    }
    
    private void jcbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionActionPerformed
        // TODO add your handling code here:
        String seleccion=(String)jcbSeleccion.getSelectedItem();
        if(seleccion.equals("Registrar")){
            jtfCodigo.setVisible(false);
            jbActualizar.setVisible(false);
            jbRegistrar.setVisible(true);
        }else if(seleccion.equals("Modificar")){
            jtfCodigo.setVisible(true);
            jbActualizar.setVisible(true);
            jbRegistrar.setVisible(false);
        }
    }//GEN-LAST:event_jcbSeleccionActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        
        periodoRepository.guardar(datosPeriodo());
        multitablasRepository.guardar(datosMultitabla());
//        lecturaModal();
        JOptionPane.showMessageDialog(null, "Datos guardados");
        
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        periodoRepository.modificar(datosPeriodo());
        lecturaModal();
        JOptionPane.showMessageDialog(null, "Datos modificados");

    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyReleased
        // TODO add your handling code here:
        String codigo=jtfCodigo.getText();
        if(codigo.equals("")){
            jifDatosPrograma.setVisible(false);
            jcbNumeroDelSemestre.removeAllItems();
        }else{
            lecturaModalPeriodo();
        }
    }//GEN-LAST:event_jtfCodigoKeyReleased

    private void jcbProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProgramasActionPerformed
        // TODO add your handling code here:
        String programa_seleccionado=(String) jcbProgramas.getSelectedItem();
        int codigo_programa=0,cantidad_semestres=0;
        if(jcbProgramas!=null){
            jcbNumeroDelSemestre.setVisible(true);
            for (Programa programa : listaProgramas) {
                if(programa_seleccionado.equals(programa.getNombre())){
                    codigo_programa=programa.getPrograma_id();
                    cantidad_semestres=programa.getCantidad_semestres();
                    break;
                }
            }
            for (int i = 1; i < cantidad_semestres; i++) {
                jcbNumeroDelSemestre.addItem(String.valueOf(i));
            }
        }
    }//GEN-LAST:event_jcbProgramasActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox<String> jcbNumeroDelSemestre;
    private javax.swing.JComboBox<String> jcbProgramas;
    private javax.swing.JComboBox<String> jcbSeleccion;
    private javax.swing.JInternalFrame jifDatosPeriodo;
    private javax.swing.JInternalFrame jifDatosPrograma;
    private javax.swing.JLabel jlAño;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlCodigoDinamico;
    private javax.swing.JLabel jlCodigoPeriodo;
    private javax.swing.JLabel jlNivel;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumeroSemestre;
    private javax.swing.JLabel jlsemestre;
    private javax.swing.JTextField jtfAnioPeriodo;
    private javax.swing.JTextField jtfCodigo;
    // End of variables declaration//GEN-END:variables
}
