package Panel;

import Model.Ciudad;
import Model.Direccion;
import Model.Persona;
import Model.Programa;
import Repository.CiudadImpl;
import Repository.DireccionImpl;
import Repository.PersonaImpl;
import Repository.ProgramaImpl;
import Repository.Repository;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @Julián
 */
public class AdministrarProgramas extends javax.swing.JPanel {
    
    private static Repository programaRepository= new ProgramaImpl();
    
    public AdministrarProgramas() {
        initComponents();
        
        setSize(1000, 600); // Tamaño mediano
        jtfCodigo.setVisible(false);
        jbActualizar.setVisible(false);
        jbRegistrar.setVisible(true);
        
        jifDatosPrograma.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNombrePrograma = new javax.swing.JTextField();
        jcbSeleccion = new javax.swing.JComboBox<>();
        jbRegistrar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JTextField();
        jcbNivel = new javax.swing.JComboBox<>();
        jtfNumeroSemestres = new javax.swing.JTextField();
        jifDatosPrograma = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlNivel = new javax.swing.JLabel();
        jlNumeroSemestre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfNombrePrograma.setBackground(new java.awt.Color(166, 181, 167));
        jtfNombrePrograma.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfNombrePrograma.setForeground(new java.awt.Color(0, 0, 1));
        jtfNombrePrograma.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Nombre del Programa", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfNombrePrograma.setOpaque(true);
        add(jtfNombrePrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, -1));

        jcbSeleccion.setBackground(new java.awt.Color(178, 144, 73));
        jcbSeleccion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbSeleccion.setForeground(new java.awt.Color(0, 0, 1));
        jcbSeleccion.setMaximumRowCount(5);
        jcbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar", "Modificar" }));
        jcbSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Que desea hacer?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(0, 0, 1))); // NOI18N
        jcbSeleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionActionPerformed(evt);
            }
        });
        add(jcbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 169, 40));

        jbRegistrar.setBackground(new java.awt.Color(0, 0, 1));
        jbRegistrar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbRegistrar.setForeground(new java.awt.Color(178, 144, 73));
        jbRegistrar.setText("Registrar");
        jbRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });
        add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 100, 30));

        jbActualizar.setBackground(new java.awt.Color(0, 0, 1));
        jbActualizar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(178, 144, 73));
        jbActualizar.setText("Actualizar");
        jbActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 100, 30));

        jtfCodigo.setBackground(new java.awt.Color(178, 144, 73));
        jtfCodigo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfCodigo.setForeground(new java.awt.Color(0, 0, 1));
        jtfCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Codigo Carrera", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfCodigo.setOpaque(true);
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyReleased(evt);
            }
        });
        add(jtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 169, -1));

        jcbNivel.setBackground(new java.awt.Color(166, 181, 167));
        jcbNivel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbNivel.setForeground(new java.awt.Color(0, 0, 1));
        jcbNivel.setMaximumRowCount(5);
        jcbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregrado", "Postgrado" }));
        jcbNivel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Nivel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jcbNivel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jcbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 176, 40));

        jtfNumeroSemestres.setBackground(new java.awt.Color(166, 181, 167));
        jtfNumeroSemestres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfNumeroSemestres.setForeground(new java.awt.Color(0, 0, 1));
        jtfNumeroSemestres.setToolTipText("");
        jtfNumeroSemestres.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Numero de semestres", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfNumeroSemestres.setOpaque(true);
        add(jtfNumeroSemestres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 176, -1));

        jifDatosPrograma.setTitle("Datos de la Carrera");
        jifDatosPrograma.setVisible(true);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Codigo:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Nivel:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setText("Numeros semestres:");

        jlCodigo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlCodigo.setText("No tiene codigo");

        jlNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNombre.setText("no tiene nombre");
        jlNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlNivel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNivel.setText("No tiene nivel");

        jlNumeroSemestre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNumeroSemestre.setText("No tiene semestres");

        javax.swing.GroupLayout jifDatosProgramaLayout = new javax.swing.GroupLayout(jifDatosPrograma.getContentPane());
        jifDatosPrograma.getContentPane().setLayout(jifDatosProgramaLayout);
        jifDatosProgramaLayout.setHorizontalGroup(
            jifDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifDatosProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifDatosProgramaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jifDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumeroSemestre)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jifDatosProgramaLayout.setVerticalGroup(
            jifDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifDatosProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jifDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jifDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        add(jifDatosPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 390, 230));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Aquí podrá registrar y actualizar carreras");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 330, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("digite numero de carrera para ver si existe");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 340, 40));
    }// </editor-fold>//GEN-END:initComponents

    private Programa datosPrograma(){
        Programa p=new Programa();
        if(jcbSeleccion.getSelectedItem().equals("Modificar")){
            int codigo=Integer.parseInt(jtfCodigo.getText());
            p.setPrograma_id(codigo);
        }
        String nombre_programa=jtfNombrePrograma.getText();
        String nivel_programa=(String) jcbNivel.getSelectedItem();
        byte cantidad_semestres=Byte.parseByte(jtfNumeroSemestres.getText());
        p.setCantidad_semestres(cantidad_semestres);
        p.setNivel(nivel_programa);
        p.setNombre(nombre_programa);
        return p;
    }
    
    private void lecturaModal(){
        jifDatosPrograma.setVisible(true);
        List<Programa> listaProgramas=programaRepository.listar();
        int codigo = Integer.parseInt(jtfCodigo.getText());
        for (Programa p : listaProgramas) {
            if(codigo==p.getPrograma_id()){
                jlCodigo.setText(String.valueOf(p.getPrograma_id()));
                jlNivel.setText(p.getNivel());
                jlNombre.setText(p.getNombre());
                jlNumeroSemestre.setText(String.valueOf(p.getCantidad_semestres()));
                break;
            }
        }
    }
    
    private void jcbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionActionPerformed
        // TODO add your handling code here:
        String seleccion=(String)jcbSeleccion.getSelectedItem();
        if(seleccion.equals("Registrar")){
            jtfCodigo.setVisible(false);
            jbActualizar.setVisible(false);
            jbRegistrar.setVisible(true);
        }else if(seleccion.equals("Modificar")){
            jtfCodigo.setVisible(true);
            jbActualizar.setVisible(true);
            jbRegistrar.setVisible(false);
        }
    }//GEN-LAST:event_jcbSeleccionActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        
        programaRepository.guardar(datosPrograma());
//        lecturaModal();
        JOptionPane.showMessageDialog(null, "Datos guardados");
        
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        programaRepository.modificar(datosPrograma());
        lecturaModal();
        JOptionPane.showMessageDialog(null, "Datos modificados");

    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyReleased
        // TODO add your handling code here:
        
        String codigo=jtfCodigo.getText();
        if(codigo.equals("")){
            jifDatosPrograma.setVisible(false);
        }else{
            lecturaModal();
        }
    }//GEN-LAST:event_jtfCodigoKeyReleased

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox<String> jcbNivel;
    private javax.swing.JComboBox<String> jcbSeleccion;
    private javax.swing.JInternalFrame jifDatosPrograma;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlNivel;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumeroSemestre;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNombrePrograma;
    private javax.swing.JTextField jtfNumeroSemestres;
    // End of variables declaration//GEN-END:variables
}
