package Panel;

import Model.Persona;
import Repository.PersonaImpl;
import Repository.Repository;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 * @Julián
 */
public class VerPersonas extends javax.swing.JPanel {
    
    private static Repository repository= new PersonaImpl();
    
    public VerPersonas() {
        initComponents();
        
        setSize(1500, 1100); // Tamaño mediano¿'
//        Color colorTranslucido = new Color(255, 255, 255, 128);
        jtPersonas.setVisible(false);
        jbBuscar.setVisible(false);
        jbEnlistar.setVisible(true);
        jtfNumeroDocumento.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPersonas = new javax.swing.JTable();
        jbEnlistar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jcbOpcion = new javax.swing.JComboBox<>();
        jtfNumeroDocumento = new javax.swing.JTextField();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtPersonas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 254)));
        jtPersonas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jtPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Aquí se mostrarán los datos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtPersonas.setName(""); // NOI18N
        jScrollPane1.setViewportView(jtPersonas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 560, 320));

        jbEnlistar.setBackground(new java.awt.Color(0, 0, 1));
        jbEnlistar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbEnlistar.setForeground(new java.awt.Color(178, 144, 73));
        jbEnlistar.setText("Enlistar");
        jbEnlistar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbEnlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnlistarActionPerformed(evt);
            }
        });
        add(jbEnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 100, 30));

        jbBuscar.setBackground(new java.awt.Color(0, 0, 1));
        jbBuscar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbBuscar.setForeground(new java.awt.Color(178, 144, 73));
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(178, 144, 73), java.awt.Color.black, java.awt.Color.lightGray));
        jbBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 100, 30));

        jcbOpcion.setBackground(new java.awt.Color(178, 144, 73));
        jcbOpcion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbOpcion.setForeground(new java.awt.Color(0, 0, 1));
        jcbOpcion.setMaximumRowCount(5);
        jcbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enlistar", "Buscar" }));
        jcbOpcion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Que quieres hacer?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jcbOpcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionActionPerformed(evt);
            }
        });
        add(jcbOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 140, 40));

        jtfNumeroDocumento.setBackground(new java.awt.Color(178, 144, 73));
        jtfNumeroDocumento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfNumeroDocumento.setForeground(new java.awt.Color(0, 0, 1));
        jtfNumeroDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Numero documento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jtfNumeroDocumento.setOpaque(true);
        jtfNumeroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroDocumentoActionPerformed(evt);
            }
        });
        add(jtfNumeroDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    public DefaultTableModel obtenerModeloTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        jtPersonas.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("Tipo Documento");
        modelo.addColumn("Número Documento");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Fecha Nacimiento");
        modelo.addColumn("Género");
        
        // Obtener el modelo de la tabla
        TableColumnModel columnModel = jtPersonas.getColumnModel();

        // Definir el ancho preferido para cada columna
        columnModel.getColumn(0).setPreferredWidth(40); // ID
        columnModel.getColumn(1).setPreferredWidth(110); // Tipo Documento
        columnModel.getColumn(2).setPreferredWidth(150); // Número Documento
        columnModel.getColumn(3).setPreferredWidth(125); // Nombre
        columnModel.getColumn(4).setPreferredWidth(125); // Apellido
        columnModel.getColumn(5).setPreferredWidth(120); // Teléfono
        columnModel.getColumn(6).setPreferredWidth(120); // Fecha Nacimiento
        columnModel.getColumn(7).setPreferredWidth(100); // Género
        // Agregar columnas u otras configuraciones según tus necesidades
        return modelo;
    }

    
    private void jbEnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnlistarActionPerformed
        // TODO add your handling code here:
        List<Persona> personas = repository.listar();
        jtPersonas.setVisible(true);
        

        DefaultTableModel modelo=obtenerModeloTabla();
        
        for (Persona p : personas) {
            Object[] fila = {
                p.getId(),
                p.getTipo_documento(),
                p.getNumero_documento(),
                p.getNombre(),
                p.getApellido(),
                p.getTelefono(),
                p.getFecha_nacimiento().toString(), // Convertir LocalDate a String
                p.getGenero()
            };
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_jbEnlistarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        List<Persona> personas = repository.listar();
        // Obtener el número de documento a buscar
        int numero_documento = Integer.parseInt(jtfNumeroDocumento.getText());
        jtPersonas.setVisible(true);
        
        DefaultTableModel modelo=obtenerModeloTabla();
        
        for (Persona p : personas) {
            if(numero_documento==p.getId()){
                Object[] fila = {
                    p.getId(),
                    p.getTipo_documento(),
                    p.getNumero_documento(),
                    p.getNombre(),
                    p.getApellido(),
                    p.getTelefono(),
                    p.getFecha_nacimiento().toString(), // Convertir LocalDate a String
                    p.getGenero()
                };
                modelo.addRow(fila);
                break;
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jcbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionActionPerformed
        // TODO add your handling code here:
        String seleccion=(String)jcbOpcion.getSelectedItem();
        if(seleccion.equals("Enlistar")){
            jbBuscar.setVisible(false);
            jtfNumeroDocumento.setVisible(false);
            jbEnlistar.setVisible(true);
        }else if(seleccion.equals("Buscar")){
            jbEnlistar.setVisible(false);
            jbBuscar.setVisible(true);
            jtfNumeroDocumento.setVisible(true);
        }
    }//GEN-LAST:event_jcbOpcionActionPerformed

    private void jtfNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroDocumentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEnlistar;
    private javax.swing.JComboBox<String> jcbOpcion;
    public javax.swing.JTable jtPersonas;
    private javax.swing.JTextField jtfNumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
